import type { Metadata } from "next";
import { LegalDocument } from "@/components/legal-document";

export const metadata: Metadata = {
  title: "Privacy",
  description:
    "The StackOrcs privacy notice covering collection, use, disclosure, retention, and individual rights.",
};

export default function PrivacyPage() {
  return (
    <LegalDocument
      eyebrow="Privacy notice"
      title="Your data, clearly governed"
      summary="This notice explains how StackOrcs controls personal data collected through this website, the purposes for which it is used, the service providers involved, and the rights available to each individual."
      sections={[
        {
          title: "Controller and scope",
          content: (
            <>
              <p>
                StackOrcs is the controller of personal data submitted through
                this website and used for its own business communications. This
                notice applies to website visits, project inquiries, Field Notes
                subscriptions, and direct communications arising from them.
              </p>
              <p>
                A separate client agreement governs personal data processed by
                StackOrcs on a client&apos;s instructions. Third-party websites
                reached through external links operate under their own notices.
              </p>
            </>
          ),
        },
        {
          title: "Data we collect",
          content: (
            <ul>
              <li>
                <strong>Inquiry data:</strong> name, work email, company,
                requested capability, timeline, project context, and any details
                included in the message.
              </li>
              <li>
                <strong>Subscription data:</strong> name, email address,
                subscription status, and delivery events needed to operate Field
                Notes.
              </li>
              <li>
                <strong>Service data:</strong> IP address, browser and device
                information, requested route, timestamp, security signals, and
                diagnostic records generated by hosting and delivery systems.
              </li>
              <li>
                <strong>Communication data:</strong> messages, attachments, and
                the business record of StackOrcs&apos; response.
              </li>
            </ul>
          ),
        },
        {
          title: "Purposes and authority",
          content: (
            <>
              <p>StackOrcs processes personal data to:</p>
              <ul>
                <li>evaluate and respond to a requested business engagement;</li>
                <li>deliver and administer a publication you requested;</li>
                <li>secure, operate, diagnose, and improve the website;</li>
                <li>maintain necessary business and consent records; and</li>
                <li>establish, exercise, or defend legal rights and comply with law.</li>
              </ul>
              <p>
                Processing is based on consent where you subscribe or otherwise
                choose to provide it, on steps you request before a potential
                engagement, and on legitimate operational or legal requirements
                permitted by applicable law. Consent may be withdrawn at any
                time without affecting processing already completed lawfully.
              </p>
            </>
          ),
        },
        {
          title: "Service providers and transfers",
          content: (
            <>
              <p>
                StackOrcs does not sell personal data and does not disclose it
                for third-party advertising. Vercel provides website hosting and
                delivery infrastructure. Resend provides transactional and
                subscription email delivery. Authorized professional advisers
                or authorities receive information only when necessary for a
                defined service, legal obligation, or protection of rights.
              </p>
              <p>
                These providers may process data in countries other than the
                visitor&apos;s own. StackOrcs limits each provider to the data and
                purpose required, uses contractual and platform safeguards, and
                makes cross-border transfers only where applicable law permits.
              </p>
            </>
          ),
        },
        {
          title: "Retention and deletion",
          content: (
            <ul>
              <li>
                Inactive project inquiries are deleted or anonymized within 24
                months after the last substantive communication unless a legal
                or contractual record must be retained longer.
              </li>
              <li>
                Subscription contact data is retained until unsubscribe. A
                minimal suppression record may be retained to ensure no further
                publication is sent.
              </li>
              <li>
                Routine security and diagnostic records are retained for the
                provider-configured operational period, ordinarily no longer
                than 90 days, unless an incident or legal duty requires
                preservation.
              </li>
              <li>
                Contract, tax, dispute, and compliance records are retained for
                the period required by applicable law or the governing agreement.
              </li>
            </ul>
          ),
        },
        {
          title: "Security and cookies",
          content: (
            <>
              <p>
                StackOrcs applies access control, server-side credential
                handling, encrypted transport, input validation, rate limiting,
                and provider security controls appropriate to this website. No
                internet transmission or storage system can be guaranteed
                absolutely secure.
              </p>
              <p>
                The site does not use advertising cookies. Limited browser
                storage remembers whether the cookie notice was dismissed. Read
                the <a href="/cookies">cookie notice</a> for the current storage
                details.
              </p>
            </>
          ),
        },
        {
          title: "Your rights",
          content: (
            <>
              <p>
                Subject to applicable law, you may request access to personal
                data held about you, a summary of its processing and recipients,
                correction or completion, erasure, withdrawal of consent, and
                grievance resolution. Where available by law, you may also
                nominate another individual to exercise your rights in the event
                of death or incapacity.
              </p>
              <p>
                Submit a privacy request through the contact page using the
                subject “Privacy request.” StackOrcs may verify identity before
                acting and will respond within the period required by applicable
                law. If a request cannot be fulfilled, the response will explain
                the applicable reason and available escalation route.
              </p>
            </>
          ),
        },
        {
          title: "Children and changes",
          content: (
            <>
              <p>
                StackOrcs provides business services and does not knowingly
                solicit personal data from anyone under 18. If such data is
                identified, it will be deleted unless retention is legally
                required.
              </p>
              <p>
                Material changes to this notice are published on this page with
                a revised update date. Where law requires additional notice or
                renewed consent, StackOrcs will provide it before the change
                takes effect for the affected processing.
              </p>
            </>
          ),
        },
      ]}
    />
  );
}
